name: ci
on:
  push:
    paths:
      - "openebs-monitoring/**"
  pull_request:
    paths:
      - "openebs-monitoring/**"
env:
  golang-version: "1.15"
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Jsonnet linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: lint
        run: |
          cd openebs-monitoring && make --always-make lint
  fmt:
    runs-on: ubuntu-latest
    name: Jsonnet formatter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd openebs-monitoring && make --always-make fmt && git diff --exit-code
  generate:
    runs-on: ubuntu-latest
    name: Generate openebs-monitoring-stack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup-go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.golang-version }}
      - name: Generate yamls
        run: |
          cd openebs-monitoring && make --always-make generate && git diff --exit-code
